#!/bin/bash

claude mcp add --transport http context7 https://mcp.context7.com/mcp -s user
claude mcp add --transport http github https://api.githubcopilot.com/mcp -H "Authorization: Bearer YOUR_GITHUB_PAT" -s user